baseurl = "http://helloworldeverything.com/"
title = "Hello World Everything"
theme = "hugo-universal-theme"
languageCode = "en-us"



# Define the number of posts per page
paginate = 10

googleAnalytics = "UA-58765047-2"


[[params.menu]]
    name = "Home"
    url  = "/"
    weight = 1

[[params.menu]]
    name = "Blog"
    url  = "/blog/"
    weight = 2

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.recent_posts]
    enable = true
    title = "Say hello to my posts"
    subtitle = "."
